yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@vue/babel-preset-app@*":
    peerDependencies:
      vue: ^2.6.10
  "@vue/cli-plugin-typescript@*":
    dependencies:
      babel-loader: "*"
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/babel-preset-app": "*"
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-e2e-nightwatch": "*"
      "@vue/cli-plugin-eslint": "*"
      "@vue/cli-plugin-pwa": "*"
      "@vue/cli-plugin-typescript": "*"
      "@vue/cli-plugin-unit-jest": "*"
      vue-cli-plugin-tauri: "*"
  "@vue/babel-plugin-jsx@*":
    peerDependencies:
      "@babel/core": "*"
  babel-loader@*:
    dependencies:
      "@babel/core": "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      vue-template-compiler: "*"
    peerDependencies:
      typescript: "*"
  vue-eslint-parser@*:
    dependencies:
      babel-eslint: "*"
  "@yzfe/vue-svgicon@*":
    peerDependencies:
      "@yzfe/svgicon-loader": "*"
  vue-loader@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      webpack: "*"

